// Countries with a representative IANA time zone (capital/primary zone).
// Used by Settings → Region and the header clock.
export const COUNTRIES = [
  { name: 'Afghanistan', tz: 'Asia/Kabul' },
  { name: 'Albania', tz: 'Europe/Tirane' },
  { name: 'Algeria', tz: 'Africa/Algiers' },
  { name: 'Angola', tz: 'Africa/Luanda' },
  { name: 'Argentina', tz: 'America/Argentina/Buenos_Aires' },
  { name: 'Armenia', tz: 'Asia/Yerevan' },
  { name: 'Australia', tz: 'Australia/Sydney' },
  { name: 'Austria', tz: 'Europe/Vienna' },
  { name: 'Azerbaijan', tz: 'Asia/Baku' },
  { name: 'Bahrain', tz: 'Asia/Bahrain' },
  { name: 'Bangladesh', tz: 'Asia/Dhaka' },
  { name: 'Belarus', tz: 'Europe/Minsk' },
  { name: 'Belgium', tz: 'Europe/Brussels' },
  { name: 'Benin', tz: 'Africa/Porto-Novo' },
  { name: 'Bhutan', tz: 'Asia/Thimphu' },
  { name: 'Bolivia', tz: 'America/La_Paz' },
  { name: 'Bosnia and Herzegovina', tz: 'Europe/Sarajevo' },
  { name: 'Botswana', tz: 'Africa/Gaborone' },
  { name: 'Brazil', tz: 'America/Sao_Paulo' },
  { name: 'Brunei', tz: 'Asia/Brunei' },
  { name: 'Bulgaria', tz: 'Europe/Sofia' },
  { name: 'Burkina Faso', tz: 'Africa/Ouagadougou' },
  { name: 'Cambodia', tz: 'Asia/Phnom_Penh' },
  { name: 'Cameroon', tz: 'Africa/Douala' },
  { name: 'Canada', tz: 'America/Toronto' },
  { name: 'Chad', tz: 'Africa/Ndjamena' },
  { name: 'Chile', tz: 'America/Santiago' },
  { name: 'China', tz: 'Asia/Shanghai' },
  { name: 'Colombia', tz: 'America/Bogota' },
  { name: 'Congo (DRC)', tz: 'Africa/Kinshasa' },
  { name: 'Costa Rica', tz: 'America/Costa_Rica' },
  { name: "Côte d'Ivoire", tz: 'Africa/Abidjan' },
  { name: 'Croatia', tz: 'Europe/Zagreb' },
  { name: 'Cuba', tz: 'America/Havana' },
  { name: 'Cyprus', tz: 'Asia/Nicosia' },
  { name: 'Czechia', tz: 'Europe/Prague' },
  { name: 'Denmark', tz: 'Europe/Copenhagen' },
  { name: 'Djibouti', tz: 'Africa/Djibouti' },
  { name: 'Dominican Republic', tz: 'America/Santo_Domingo' },
  { name: 'Ecuador', tz: 'America/Guayaquil' },
  { name: 'Egypt', tz: 'Africa/Cairo' },
  { name: 'El Salvador', tz: 'America/El_Salvador' },
  { name: 'Estonia', tz: 'Europe/Tallinn' },
  { name: 'Ethiopia', tz: 'Africa/Addis_Ababa' },
  { name: 'Finland', tz: 'Europe/Helsinki' },
  { name: 'France', tz: 'Europe/Paris' },
  { name: 'Gabon', tz: 'Africa/Libreville' },
  { name: 'Georgia', tz: 'Asia/Tbilisi' },
  { name: 'Germany', tz: 'Europe/Berlin' },
  { name: 'Ghana', tz: 'Africa/Accra' },
  { name: 'Greece', tz: 'Europe/Athens' },
  { name: 'Guatemala', tz: 'America/Guatemala' },
  { name: 'Guinea', tz: 'Africa/Conakry' },
  { name: 'Honduras', tz: 'America/Tegucigalpa' },
  { name: 'Hong Kong', tz: 'Asia/Hong_Kong' },
  { name: 'Hungary', tz: 'Europe/Budapest' },
  { name: 'Iceland', tz: 'Atlantic/Reykjavik' },
  { name: 'India', tz: 'Asia/Kolkata' },
  { name: 'Indonesia', tz: 'Asia/Jakarta' },
  { name: 'Iran', tz: 'Asia/Tehran' },
  { name: 'Iraq', tz: 'Asia/Baghdad' },
  { name: 'Ireland', tz: 'Europe/Dublin' },
  { name: 'Israel', tz: 'Asia/Jerusalem' },
  { name: 'Italy', tz: 'Europe/Rome' },
  { name: 'Jamaica', tz: 'America/Jamaica' },
  { name: 'Japan', tz: 'Asia/Tokyo' },
  { name: 'Jordan', tz: 'Asia/Amman' },
  { name: 'Kazakhstan', tz: 'Asia/Almaty' },
  { name: 'Kenya', tz: 'Africa/Nairobi' },
  { name: 'Kuwait', tz: 'Asia/Kuwait' },
  { name: 'Kyrgyzstan', tz: 'Asia/Bishkek' },
  { name: 'Laos', tz: 'Asia/Vientiane' },
  { name: 'Latvia', tz: 'Europe/Riga' },
  { name: 'Lebanon', tz: 'Asia/Beirut' },
  { name: 'Libya', tz: 'Africa/Tripoli' },
  { name: 'Lithuania', tz: 'Europe/Vilnius' },
  { name: 'Luxembourg', tz: 'Europe/Luxembourg' },
  { name: 'Macau', tz: 'Asia/Macau' },
  { name: 'Madagascar', tz: 'Indian/Antananarivo' },
  { name: 'Malawi', tz: 'Africa/Blantyre' },
  { name: 'Malaysia', tz: 'Asia/Kuala_Lumpur' },
  { name: 'Maldives', tz: 'Indian/Maldives' },
  { name: 'Mali', tz: 'Africa/Bamako' },
  { name: 'Malta', tz: 'Europe/Malta' },
  { name: 'Mauritania', tz: 'Africa/Nouakchott' },
  { name: 'Mauritius', tz: 'Indian/Mauritius' },
  { name: 'Mexico', tz: 'America/Mexico_City' },
  { name: 'Moldova', tz: 'Europe/Chisinau' },
  { name: 'Mongolia', tz: 'Asia/Ulaanbaatar' },
  { name: 'Montenegro', tz: 'Europe/Podgorica' },
  { name: 'Morocco', tz: 'Africa/Casablanca' },
  { name: 'Mozambique', tz: 'Africa/Maputo' },
  { name: 'Myanmar', tz: 'Asia/Yangon' },
  { name: 'Namibia', tz: 'Africa/Windhoek' },
  { name: 'Nepal', tz: 'Asia/Kathmandu' },
  { name: 'Netherlands', tz: 'Europe/Amsterdam' },
  { name: 'New Zealand', tz: 'Pacific/Auckland' },
  { name: 'Nicaragua', tz: 'America/Managua' },
  { name: 'Niger', tz: 'Africa/Niamey' },
  { name: 'Nigeria', tz: 'Africa/Lagos' },
  { name: 'North Macedonia', tz: 'Europe/Skopje' },
  { name: 'Norway', tz: 'Europe/Oslo' },
  { name: 'Oman', tz: 'Asia/Muscat' },
  { name: 'Pakistan', tz: 'Asia/Karachi' },
  { name: 'Palestine', tz: 'Asia/Hebron' },
  { name: 'Panama', tz: 'America/Panama' },
  { name: 'Papua New Guinea', tz: 'Pacific/Port_Moresby' },
  { name: 'Paraguay', tz: 'America/Asuncion' },
  { name: 'Peru', tz: 'America/Lima' },
  { name: 'Philippines', tz: 'Asia/Manila' },
  { name: 'Poland', tz: 'Europe/Warsaw' },
  { name: 'Portugal', tz: 'Europe/Lisbon' },
  { name: 'Qatar', tz: 'Asia/Qatar' },
  { name: 'Romania', tz: 'Europe/Bucharest' },
  { name: 'Russia', tz: 'Europe/Moscow' },
  { name: 'Rwanda', tz: 'Africa/Kigali' },
  { name: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { name: 'Senegal', tz: 'Africa/Dakar' },
  { name: 'Serbia', tz: 'Europe/Belgrade' },
  { name: 'Sierra Leone', tz: 'Africa/Freetown' },
  { name: 'Singapore', tz: 'Asia/Singapore' },
  { name: 'Slovakia', tz: 'Europe/Bratislava' },
  { name: 'Slovenia', tz: 'Europe/Ljubljana' },
  { name: 'Somalia', tz: 'Africa/Mogadishu' },
  { name: 'South Africa', tz: 'Africa/Johannesburg' },
  { name: 'South Korea', tz: 'Asia/Seoul' },
  { name: 'South Sudan', tz: 'Africa/Juba' },
  { name: 'Spain', tz: 'Europe/Madrid' },
  { name: 'Sri Lanka', tz: 'Asia/Colombo' },
  { name: 'Sudan', tz: 'Africa/Khartoum' },
  { name: 'Sweden', tz: 'Europe/Stockholm' },
  { name: 'Switzerland', tz: 'Europe/Zurich' },
  { name: 'Syria', tz: 'Asia/Damascus' },
  { name: 'Taiwan', tz: 'Asia/Taipei' },
  { name: 'Tajikistan', tz: 'Asia/Dushanbe' },
  { name: 'Tanzania', tz: 'Africa/Dar_es_Salaam' },
  { name: 'Thailand', tz: 'Asia/Bangkok' },
  { name: 'Togo', tz: 'Africa/Lome' },
  { name: 'Tunisia', tz: 'Africa/Tunis' },
  { name: 'Turkey', tz: 'Europe/Istanbul' },
  { name: 'Turkmenistan', tz: 'Asia/Ashgabat' },
  { name: 'Uganda', tz: 'Africa/Kampala' },
  { name: 'Ukraine', tz: 'Europe/Kiev' },
  { name: 'United Arab Emirates', tz: 'Asia/Dubai' },
  { name: 'United Kingdom', tz: 'Europe/London' },
  { name: 'United States', tz: 'America/New_York' },
  { name: 'Uruguay', tz: 'America/Montevideo' },
  { name: 'Uzbekistan', tz: 'Asia/Tashkent' },
  { name: 'Venezuela', tz: 'America/Caracas' },
  { name: 'Vietnam', tz: 'Asia/Ho_Chi_Minh' },
  { name: 'Yemen', tz: 'Asia/Aden' },
  { name: 'Zambia', tz: 'Africa/Lusaka' },
  { name: 'Zimbabwe', tz: 'Africa/Harare' },
];

const TZ_KEY = 'app_timezone';

// the time zone the header clock should use (saved region → else browser local)
export function getAppTimeZone() {
  try { return localStorage.getItem(TZ_KEY) || undefined; } catch { return undefined; }
}
export function setAppTimeZone(tz) {
  try { if (tz) localStorage.setItem(TZ_KEY, tz); else localStorage.removeItem(TZ_KEY); } catch { /* ignore */ }
}
